# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 20:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('percent_discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Discount must not be less than 0 percent'), django.core.validators.MaxValueValidator(100, 'Discount must not exceed 100 percent')], verbose_name='Discount (%)')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('end_date',),
            },
        ),
    ]
