# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountsection',
            name='image',
            field=models.ImageField(default='', upload_to='discount/section'),
            preserve_default=False,
        ),
    ]
