# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_discountsection_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountsection',
            options={'ordering': ('-end_date',)},
        ),
    ]
