# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 21:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180717_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(upload_to='books/file/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'Only pdf files are allowed')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[shop.validators.validate_isbn_len]),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[shop.validators.validate_price]),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(default=django.utils.timezone.now, validators=[shop.validators.validate_year_is_not_future]),
        ),
    ]
