# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180717_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.IntegerField(default=100, verbose_name='Number of pages'),
        ),
    ]
