# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180727_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
