# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[shop.validators.validate_isbn]),
        ),
    ]
