# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 08:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180809_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_url',
            field=models.URLField(blank=True, help_text="this should be provided only if you don'twant to upload a book and would rather use and book from google or any other medium. this must be a URL", max_length=400),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, help_text="this should be provided only if you don'twant to upload an image and would rather use and image from google or any other medium. this must be a URL", max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, upload_to='books/file/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'Only pdf files are allowed')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='books/%Y/%m/%d'),
        ),
    ]
