# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180722_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
